/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Alert: typeof import('./src/components/ui/alert/index').Alert
  const AlertDescription: typeof import('./src/components/ui/alert/index').AlertDescription
  const AlertTitle: typeof import('./src/components/ui/alert/index').AlertTitle
  const Avatar: typeof import('./src/components/ui/avatar/index').Avatar
  const AvatarFallback: typeof import('./src/components/ui/avatar/index').AvatarFallback
  const AvatarImage: typeof import('./src/components/ui/avatar/index').AvatarImage
  const Badge: typeof import('./src/components/ui/badge/index').Badge
  const Button: typeof import('./src/components/ui/button/index').Button
  const ButtonGroup: typeof import('./src/components/ui/button-group/index').ButtonGroup
  const ButtonGroupSeparator: typeof import('./src/components/ui/button-group/index').ButtonGroupSeparator
  const ButtonGroupText: typeof import('./src/components/ui/button-group/index').ButtonGroupText
  const Card: typeof import('./src/components/ui/card/index').Card
  const CardContent: typeof import('./src/components/ui/card/index').CardContent
  const CardDescription: typeof import('./src/components/ui/card/index').CardDescription
  const CardHeader: typeof import('./src/components/ui/card/index').CardHeader
  const CardTitle: typeof import('./src/components/ui/card/index').CardTitle
  const ChatUtils: typeof import('./src/utils/ChatUtils').ChatUtils
  const Checkpoint: typeof import('./src/components/ai-elements/checkpoint/index').Checkpoint
  const CheckpointIcon: typeof import('./src/components/ai-elements/checkpoint/index').CheckpointIcon
  const CheckpointTrigger: typeof import('./src/components/ai-elements/checkpoint/index').CheckpointTrigger
  const CheckpointTypeSchema: typeof import('./src/utils/interface').CheckpointTypeSchema
  const CodeBlock: typeof import('./src/components/ai-elements/code-block/index').CodeBlock
  const CodeBlockCopyButton: typeof import('./src/components/ai-elements/code-block/index').CodeBlockCopyButton
  const CodeBlockKey: typeof import('./src/components/ai-elements/code-block/context').CodeBlockKey
  const Collapsible: typeof import('./src/components/ui/collapsible/index').Collapsible
  const CollapsibleContent: typeof import('./src/components/ui/collapsible/index').CollapsibleContent
  const CollapsibleTrigger: typeof import('./src/components/ui/collapsible/index').CollapsibleTrigger
  const Command: typeof import('./src/components/ui/command/index').Command
  const CommandDialog: typeof import('./src/components/ui/command/index').CommandDialog
  const CommandEmpty: typeof import('./src/components/ui/command/index').CommandEmpty
  const CommandGroup: typeof import('./src/components/ui/command/index').CommandGroup
  const CommandInput: typeof import('./src/components/ui/command/index').CommandInput
  const CommandItem: typeof import('./src/components/ui/command/index').CommandItem
  const CommandList: typeof import('./src/components/ui/command/index').CommandList
  const CommandSeparator: typeof import('./src/components/ui/command/index').CommandSeparator
  const CommandShortcut: typeof import('./src/components/ui/command/index').CommandShortcut
  const Confirmation: typeof import('./src/components/ai-elements/confirmation/index').Confirmation
  const ConfirmationAccepted: typeof import('./src/components/ai-elements/confirmation/index').ConfirmationAccepted
  const ConfirmationAction: typeof import('./src/components/ai-elements/confirmation/index').ConfirmationAction
  const ConfirmationActions: typeof import('./src/components/ai-elements/confirmation/index').ConfirmationActions
  const ConfirmationKey: typeof import('./src/components/ai-elements/confirmation/context').ConfirmationKey
  const ConfirmationRejected: typeof import('./src/components/ai-elements/confirmation/index').ConfirmationRejected
  const ConfirmationRequest: typeof import('./src/components/ai-elements/confirmation/index').ConfirmationRequest
  const ConfirmationTitle: typeof import('./src/components/ai-elements/confirmation/index').ConfirmationTitle
  const Context: typeof import('./src/components/ai-elements/context/index').Context
  const ContextCacheUsage: typeof import('./src/components/ai-elements/context/index').ContextCacheUsage
  const ContextContent: typeof import('./src/components/ai-elements/context/index').ContextContent
  const ContextContentBody: typeof import('./src/components/ai-elements/context/index').ContextContentBody
  const ContextContentFooter: typeof import('./src/components/ai-elements/context/index').ContextContentFooter
  const ContextContentHeader: typeof import('./src/components/ai-elements/context/index').ContextContentHeader
  const ContextIcon: typeof import('./src/components/ai-elements/context/index').ContextIcon
  const ContextInputUsage: typeof import('./src/components/ai-elements/context/index').ContextInputUsage
  const ContextKey: typeof import('./src/components/ai-elements/context/context').ContextKey
  const ContextOutputUsage: typeof import('./src/components/ai-elements/context/index').ContextOutputUsage
  const ContextReasoningUsage: typeof import('./src/components/ai-elements/context/index').ContextReasoningUsage
  const ContextTrigger: typeof import('./src/components/ai-elements/context/index').ContextTrigger
  const Conversation: typeof import('./src/components/ai-elements/conversation/index').Conversation
  const ConversationContent: typeof import('./src/components/ai-elements/conversation/index').ConversationContent
  const ConversationEmptyState: typeof import('./src/components/ai-elements/conversation/index').ConversationEmptyState
  const ConversationItemSchema: typeof import('./src/utils/interface').ConversationItemSchema
  const ConversationSchema: typeof import('./src/utils/interface').ConversationSchema
  const ConversationScrollButton: typeof import('./src/components/ai-elements/conversation/index').ConversationScrollButton
  const Cryption: typeof import('./src/utils/Cryption').Cryption
  const DEFAULT_AVATARS: typeof import('./src/utils/meetingInterface').DEFAULT_AVATARS
  const DEFAULT_COLORS: typeof import('./src/utils/meetingInterface').DEFAULT_COLORS
  const Dialog: typeof import('./src/components/ui/dialog/index').Dialog
  const DialogClose: typeof import('./src/components/ui/dialog/index').DialogClose
  const DialogContent: typeof import('./src/components/ui/dialog/index').DialogContent
  const DialogDescription: typeof import('./src/components/ui/dialog/index').DialogDescription
  const DialogFooter: typeof import('./src/components/ui/dialog/index').DialogFooter
  const DialogHeader: typeof import('./src/components/ui/dialog/index').DialogHeader
  const DialogOverlay: typeof import('./src/components/ui/dialog/index').DialogOverlay
  const DialogScrollContent: typeof import('./src/components/ui/dialog/index').DialogScrollContent
  const DialogTitle: typeof import('./src/components/ui/dialog/index').DialogTitle
  const DialogTrigger: typeof import('./src/components/ui/dialog/index').DialogTrigger
  const DropdownMenu: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./src/components/ui/dropdown-menu/index').DropdownMenuTrigger
  const EffectScope: typeof import('vue').EffectScope
  const ElMessage: typeof import('element-plus/es').ElMessage
  const ElMessageBox: typeof import('element-plus/es').ElMessageBox
  const GloscStoreApi: typeof import('./src/utils/GloscStoreApi').GloscStoreApi
  const HoverCard: typeof import('./src/components/ui/hover-card/index').HoverCard
  const HoverCardContent: typeof import('./src/components/ui/hover-card/index').HoverCardContent
  const HoverCardTrigger: typeof import('./src/components/ui/hover-card/index').HoverCardTrigger
  const Image: typeof import('./src/components/ai-elements/image/index').Image
  const Input: typeof import('./src/components/ui/input/index').Input
  const InputGroup: typeof import('./src/components/ui/input-group/index').InputGroup
  const InputGroupAddon: typeof import('./src/components/ui/input-group/index').InputGroupAddon
  const InputGroupButton: typeof import('./src/components/ui/input-group/index').InputGroupButton
  const InputGroupInput: typeof import('./src/components/ui/input-group/index').InputGroupInput
  const InputGroupText: typeof import('./src/components/ui/input-group/index').InputGroupText
  const InputGroupTextarea: typeof import('./src/components/ui/input-group/index').InputGroupTextarea
  const Label: typeof import('./src/components/ui/label/index').Label
  const Loader: typeof import('./src/components/ai-elements/loader/index').Loader
  const LoaderIcon: typeof import('./src/components/ai-elements/loader/index').LoaderIcon
  const McpServerSchema: typeof import('./src/utils/interface').McpServerSchema
  const McpUtils: typeof import('./src/utils/McpUtils').McpUtils
  const MeetingItemSchema: typeof import('./src/utils/meetingInterface').MeetingItemSchema
  const MeetingMessageSchema: typeof import('./src/utils/meetingInterface').MeetingMessageSchema
  const MeetingRoleSchema: typeof import('./src/utils/meetingInterface').MeetingRoleSchema
  const MeetingSchema: typeof import('./src/utils/meetingInterface').MeetingSchema
  const Message: typeof import('./src/components/ai-elements/message/index').Message
  const MessageAction: typeof import('./src/components/ai-elements/message/index').MessageAction
  const MessageActions: typeof import('./src/components/ai-elements/message/index').MessageActions
  const MessageAttachment: typeof import('./src/components/ai-elements/message/index').MessageAttachment
  const MessageAttachments: typeof import('./src/components/ai-elements/message/index').MessageAttachments
  const MessageAvatar: typeof import('./src/components/ai-elements/message/index').MessageAvatar
  const MessageBranch: typeof import('./src/components/ai-elements/message/index').MessageBranch
  const MessageBranchContent: typeof import('./src/components/ai-elements/message/index').MessageBranchContent
  const MessageBranchKey: typeof import('./src/components/ai-elements/message/context').MessageBranchKey
  const MessageBranchNext: typeof import('./src/components/ai-elements/message/index').MessageBranchNext
  const MessageBranchPage: typeof import('./src/components/ai-elements/message/index').MessageBranchPage
  const MessageBranchPrevious: typeof import('./src/components/ai-elements/message/index').MessageBranchPrevious
  const MessageBranchSelector: typeof import('./src/components/ai-elements/message/index').MessageBranchSelector
  const MessageContent: typeof import('./src/components/ai-elements/message/index').MessageContent
  const MessageResponse: typeof import('./src/components/ai-elements/message/index').MessageResponse
  const MessageToolbar: typeof import('./src/components/ai-elements/message/index').MessageToolbar
  const ModelInfoSchema: typeof import('./src/utils/interface').ModelInfoSchema
  const ModelSelector: typeof import('./src/components/ai-elements/model-selector/index').ModelSelector
  const ModelSelectorContent: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorContent
  const ModelSelectorDialog: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorDialog
  const ModelSelectorEmpty: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorEmpty
  const ModelSelectorGroup: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorGroup
  const ModelSelectorInput: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorInput
  const ModelSelectorItem: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorItem
  const ModelSelectorList: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorList
  const ModelSelectorLogo: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorLogo
  const ModelSelectorLogoGroup: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorLogoGroup
  const ModelSelectorName: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorName
  const ModelSelectorSeparator: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorSeparator
  const ModelSelectorShortcut: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorShortcut
  const ModelSelectorTrigger: typeof import('./src/components/ai-elements/model-selector/index').ModelSelectorTrigger
  const ModelsResponseSchema: typeof import('./src/utils/interface').ModelsResponseSchema
  const PROMPT_INPUT_KEY: typeof import('./src/components/ai-elements/prompt-input/types').PROMPT_INPUT_KEY
  const Popover: typeof import('./src/components/ui/popover/index').Popover
  const PopoverAnchor: typeof import('./src/components/ui/popover/index').PopoverAnchor
  const PopoverContent: typeof import('./src/components/ui/popover/index').PopoverContent
  const PopoverTrigger: typeof import('./src/components/ui/popover/index').PopoverTrigger
  const Progress: typeof import('./src/components/ui/progress/index').Progress
  const PromptInput: typeof import('./src/components/ai-elements/prompt-input/index').PromptInput
  const PromptInputActionAddAttachments: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputActionAddAttachments
  const PromptInputActionMenu: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputActionMenu
  const PromptInputActionMenuContent: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputActionMenuContent
  const PromptInputActionMenuItem: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputActionMenuItem
  const PromptInputActionMenuTrigger: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputActionMenuTrigger
  const PromptInputAttachment: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputAttachment
  const PromptInputAttachments: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputAttachments
  const PromptInputBody: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputBody
  const PromptInputButton: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputButton
  const PromptInputCommand: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputCommand
  const PromptInputCommandEmpty: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputCommandEmpty
  const PromptInputCommandGroup: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputCommandGroup
  const PromptInputCommandInput: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputCommandInput
  const PromptInputCommandItem: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputCommandItem
  const PromptInputCommandList: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputCommandList
  const PromptInputCommandSeparator: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputCommandSeparator
  const PromptInputFooter: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputFooter
  const PromptInputHeader: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputHeader
  const PromptInputHoverCard: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputHoverCard
  const PromptInputHoverCardContent: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputHoverCardContent
  const PromptInputHoverCardTrigger: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputHoverCardTrigger
  const PromptInputProvider: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputProvider
  const PromptInputSelect: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputSelect
  const PromptInputSelectContent: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputSelectContent
  const PromptInputSelectItem: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputSelectItem
  const PromptInputSelectTrigger: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputSelectTrigger
  const PromptInputSelectValue: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputSelectValue
  const PromptInputSpeechButton: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputSpeechButton
  const PromptInputSubmit: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputSubmit
  const PromptInputTab: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputTab
  const PromptInputTabBody: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputTabBody
  const PromptInputTabItem: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputTabItem
  const PromptInputTabLabel: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputTabLabel
  const PromptInputTabsList: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputTabsList
  const PromptInputTextarea: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputTextarea
  const PromptInputTools: typeof import('./src/components/ai-elements/prompt-input/index').PromptInputTools
  const QueueNodeSchema: typeof import('./src/utils/meetingInterface').QueueNodeSchema
  const Reasoning: typeof import('./src/components/ai-elements/reasoning/index').Reasoning
  const ReasoningContent: typeof import('./src/components/ai-elements/reasoning/index').ReasoningContent
  const ReasoningKey: typeof import('./src/components/ai-elements/reasoning/context').ReasoningKey
  const ReasoningTrigger: typeof import('./src/components/ai-elements/reasoning/index').ReasoningTrigger
  const Select: typeof import('./src/components/ui/select/index').Select
  const SelectContent: typeof import('./src/components/ui/select/index').SelectContent
  const SelectGroup: typeof import('./src/components/ui/select/index').SelectGroup
  const SelectItem: typeof import('./src/components/ui/select/index').SelectItem
  const SelectItemText: typeof import('./src/components/ui/select/index').SelectItemText
  const SelectLabel: typeof import('./src/components/ui/select/index').SelectLabel
  const SelectScrollDownButton: typeof import('./src/components/ui/select/index').SelectScrollDownButton
  const SelectScrollUpButton: typeof import('./src/components/ui/select/index').SelectScrollUpButton
  const SelectSeparator: typeof import('./src/components/ui/select/index').SelectSeparator
  const SelectTrigger: typeof import('./src/components/ui/select/index').SelectTrigger
  const SelectValue: typeof import('./src/components/ui/select/index').SelectValue
  const Separator: typeof import('./src/components/ui/separator/index').Separator
  const Shimmer: typeof import('./src/components/ai-elements/shimmer/index').Shimmer
  const Source: typeof import('./src/components/ai-elements/sources/index').Source
  const Sources: typeof import('./src/components/ai-elements/sources/index').Sources
  const SourcesContent: typeof import('./src/components/ai-elements/sources/index').SourcesContent
  const SourcesTrigger: typeof import('./src/components/ai-elements/sources/index').SourcesTrigger
  const StoreUtils: typeof import('./src/utils/StoreUtils').StoreUtils
  const StoredChatMessageSchema: typeof import('./src/utils/interface').StoredChatMessageSchema
  const Tabs: typeof import('./src/components/ui/tabs/index').Tabs
  const TabsContent: typeof import('./src/components/ui/tabs/index').TabsContent
  const TabsList: typeof import('./src/components/ui/tabs/index').TabsList
  const TabsTrigger: typeof import('./src/components/ui/tabs/index').TabsTrigger
  const Task: typeof import('./src/components/ai-elements/task/index').Task
  const TaskContent: typeof import('./src/components/ai-elements/task/index').TaskContent
  const TaskItem: typeof import('./src/components/ai-elements/task/index').TaskItem
  const TaskItemFile: typeof import('./src/components/ai-elements/task/index').TaskItemFile
  const TaskTrigger: typeof import('./src/components/ai-elements/task/index').TaskTrigger
  const TauriStdioTransport: typeof import('./src/utils/TauriStdioTransport').TauriStdioTransport
  const Textarea: typeof import('./src/components/ui/textarea/index').Textarea
  const TokensWithCost: typeof import('./src/components/ai-elements/context/index').TokensWithCost
  const Tool: typeof import('./src/components/ai-elements/tool/index').Tool
  const ToolContent: typeof import('./src/components/ai-elements/tool/index').ToolContent
  const ToolHeader: typeof import('./src/components/ai-elements/tool/index').ToolHeader
  const ToolInput: typeof import('./src/components/ai-elements/tool/index').ToolInput
  const ToolOutput: typeof import('./src/components/ai-elements/tool/index').ToolOutput
  const Tooltip: typeof import('./src/components/ui/tooltip/index').Tooltip
  const TooltipContent: typeof import('./src/components/ui/tooltip/index').TooltipContent
  const TooltipProvider: typeof import('./src/components/ui/tooltip/index').TooltipProvider
  const TooltipTrigger: typeof import('./src/components/ui/tooltip/index').TooltipTrigger
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const alertVariants: typeof import('./src/components/ui/alert/index').alertVariants
  const badgeVariants: typeof import('./src/components/ui/badge/index').badgeVariants
  const buttonGroupVariants: typeof import('./src/components/ui/button-group/index').buttonGroupVariants
  const buttonVariants: typeof import('./src/components/ui/button/index').buttonVariants
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createBuiltinTools: typeof import('./src/utils/BuiltinTools').createBuiltinTools
  const createMarkdownParser: typeof import('./src/utils/MarkdownIt').createMarkdownParser
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const decodeBase64Url: typeof import('./src/utils/McpServerImport').decodeBase64Url
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const ensureMonacoWorkers: typeof import('./src/utils/MonacoSetup').ensureMonacoWorkers
  const fetchAvailableModels: typeof import('./src/utils/ModelApi').fetchAvailableModels
  const formatModelName: typeof import('./src/utils/ModelApi').formatModelName
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getModelProvider: typeof import('./src/utils/ModelApi').getModelProvider
  const getStorePricingTypeFromEnv: typeof import('./src/utils/StoreToolAccess').getStorePricingTypeFromEnv
  const getStoreSlug: typeof import('./src/utils/StoreToolAccess').getStoreSlug
  const getStoreToolAccessInfoFromEnv: typeof import('./src/utils/StoreToolAccess').getStoreToolAccessInfoFromEnv
  const groupModelsByProvider: typeof import('./src/utils/ModelApi').groupModelsByProvider
  const h: typeof import('vue').h
  const highlightCode: typeof import('./src/components/ai-elements/code-block/utils').highlightCode
  const inject: typeof import('vue').inject
  const inputGroupAddonVariants: typeof import('./src/components/ui/input-group/index').inputGroupAddonVariants
  const inputGroupButtonVariants: typeof import('./src/components/ui/input-group/index').inputGroupButtonVariants
  const installStoreTool: typeof import('./src/utils/StoreToolInstaller').installStoreTool
  const isMcpServerEqual: typeof import('./src/utils/McpServerImport').isMcpServerEqual
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isStoreInstalledServer: typeof import('./src/utils/StoreToolAccess').isStoreInstalledServer
  const isStoreToolBlocked: typeof import('./src/utils/StoreToolAccess').isStoreToolBlocked
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const meetingMessagesToUiMessages: typeof import('./src/utils/MeetingUiMessageAdapter').meetingMessagesToUiMessages
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseMcpServerConfigs: typeof import('./src/utils/McpServerImport').parseMcpServerConfigs
  const provide: typeof import('vue').provide
  const provideCommandContext: typeof import('./src/components/ui/command/index').provideCommandContext
  const provideCommandGroupContext: typeof import('./src/components/ui/command/index').provideCommandGroupContext
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const requestGeneratedImage: typeof import('./src/utils/ImageApi').requestGeneratedImage
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const splitCommandLine: typeof import('./src/utils/McpServerImport').splitCommandLine
  const storeToRefs: typeof import('pinia').storeToRefs
  const storeUtils: typeof import('./src/utils/StoreUtils').storeUtils
  const stripJsonComments: typeof import('./src/utils/McpServerImport').stripJsonComments
  const syncInstalledStoreToolsAccess: typeof import('./src/utils/StoreToolAccess').syncInstalledStoreToolsAccess
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const updateStoreTool: typeof import('./src/utils/StoreToolInstaller').updateStoreTool
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./src/stores/auth').useAuthStore
  const useChatStore: typeof import('./src/stores/chat').useChatStore
  const useCommand: typeof import('./src/components/ui/command/index').useCommand
  const useCommandGroup: typeof import('./src/components/ui/command/index').useCommandGroup
  const useConfirmationContext: typeof import('./src/components/ai-elements/confirmation/context').useConfirmationContext
  const useContextValue: typeof import('./src/components/ai-elements/context/context').useContextValue
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useMcpStore: typeof import('./src/stores/mcp').useMcpStore
  const useMeetingStore: typeof import('./src/stores/meeting').useMeetingStore
  const useMessageBranchContext: typeof import('./src/components/ai-elements/message/context').useMessageBranchContext
  const useModel: typeof import('vue').useModel
  const usePromptInput: typeof import('./src/components/ai-elements/prompt-input/context').usePromptInput
  const usePromptInputProvider: typeof import('./src/components/ai-elements/prompt-input/context').usePromptInputProvider
  const useReasoningContext: typeof import('./src/components/ai-elements/reasoning/context').useReasoningContext
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSettingsStore: typeof import('./src/stores/settings').useSettingsStore
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUiStore: typeof import('./src/stores/ui').useUiStore
  const useWorkspaceChatStore: typeof import('./src/stores/workspaceChat').useWorkspaceChatStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AuthUserPublic } from './src/stores/auth'
  import('./src/stores/auth')
  // @ts-ignore
  export type { BuiltinToolKind, BuiltinToolsEnabled } from './src/stores/settings'
  import('./src/stores/settings')
  // @ts-ignore
  export type { WorkspaceChatApiMode, WorkspaceFileContextMode, WorkspaceBuiltinToolKind, WorkspaceBuiltinToolsEnabled, WorkspaceConversation } from './src/stores/workspaceChat'
  import('./src/stores/workspaceChat')
  // @ts-ignore
  export type { ClientTool, BuiltinToolsOptions } from './src/utils/BuiltinTools'
  import('./src/utils/BuiltinTools')
  // @ts-ignore
  export type { ChatUtils } from './src/utils/ChatUtils'
  import('./src/utils/ChatUtils')
  // @ts-ignore
  export type { Cryption } from './src/utils/Cryption'
  import('./src/utils/Cryption')
  // @ts-ignore
  export type { StorePluginSource, StorePlugin, StorePluginVersion } from './src/utils/GloscStoreApi'
  import('./src/utils/GloscStoreApi')
  // @ts-ignore
  export type { GeneratedImageResult, GenerateImageRequest } from './src/utils/ImageApi'
  import('./src/utils/ImageApi')
  // @ts-ignore
  export type { McpServerImportConfig } from './src/utils/McpServerImport'
  import('./src/utils/McpServerImport')
  // @ts-ignore
  export type { McpUtils } from './src/utils/McpUtils'
  import('./src/utils/McpUtils')
  // @ts-ignore
  export type { MeetingUIMessage } from './src/utils/MeetingUiMessageAdapter'
  import('./src/utils/MeetingUiMessageAdapter')
  // @ts-ignore
  export type { StoreToolAccessStatus, StoreToolAccessInfo } from './src/utils/StoreToolAccess'
  import('./src/utils/StoreToolAccess')
  // @ts-ignore
  export type { StoreUtils } from './src/utils/StoreUtils'
  import('./src/utils/StoreUtils')
  // @ts-ignore
  export type { TauriStdioTransport } from './src/utils/TauriStdioTransport'
  import('./src/utils/TauriStdioTransport')
  // @ts-ignore
  export type { ModelInfo, ModelsResponse, StoredChatMessage, ConversationItem, CheckpointType, McpServer, ClientToolRegistry, CreateChatClientOptions } from './src/utils/interface'
  import('./src/utils/interface')
  // @ts-ignore
  export type { MeetingRole, MeetingStatus, SpeakerType, QueueNode, MeetingMessage, Meeting, MeetingItem } from './src/utils/meetingInterface'
  import('./src/utils/meetingInterface')
  // @ts-ignore
  export type { CodeBlockContext } from './src/components/ai-elements/code-block/context'
  import('./src/components/ai-elements/code-block/context')
  // @ts-ignore
  export type { ToolUIPartApproval, ConfirmationContextValue } from './src/components/ai-elements/confirmation/context'
  import('./src/components/ai-elements/confirmation/context')
  // @ts-ignore
  export type { ModelId, ContextContextValue } from './src/components/ai-elements/context/context'
  import('./src/components/ai-elements/context/context')
  // @ts-ignore
  export type { MessageBranchContextType } from './src/components/ai-elements/message/context'
  import('./src/components/ai-elements/message/context')
  // @ts-ignore
  export type { PromptInputMessage, AttachmentFile, PromptInputContext } from './src/components/ai-elements/prompt-input/types'
  import('./src/components/ai-elements/prompt-input/types')
  // @ts-ignore
  export type { ReasoningContextValue } from './src/components/ai-elements/reasoning/context'
  import('./src/components/ai-elements/reasoning/context')
  // @ts-ignore
  export type { TextShimmerProps } from './src/components/ai-elements/shimmer/Shimmer.vue'
  import('./src/components/ai-elements/shimmer/Shimmer.vue')
  // @ts-ignore
  export type { AlertVariants } from './src/components/ui/alert/index'
  import('./src/components/ui/alert/index')
  // @ts-ignore
  export type { BadgeVariants } from './src/components/ui/badge/index'
  import('./src/components/ui/badge/index')
  // @ts-ignore
  export type { ButtonGroupVariants } from './src/components/ui/button-group/index'
  import('./src/components/ui/button-group/index')
  // @ts-ignore
  export type { ButtonVariants } from './src/components/ui/button/index'
  import('./src/components/ui/button/index')
  // @ts-ignore
  export type { InputGroupVariants, InputGroupButtonVariants, InputGroupButtonProps } from './src/components/ui/input-group/index'
  import('./src/components/ui/input-group/index')
}
