/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mcp': RouteRecordInfo<
      '/mcp',
      '/mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/meeting/': RouteRecordInfo<
      '/meeting/',
      '/meeting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/meeting/[id]': RouteRecordInfo<
      '/meeting/[id]',
      '/meeting/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/plan': RouteRecordInfo<
      '/plan',
      '/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks': RouteRecordInfo<
      '/tasks',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workspace': RouteRecordInfo<
      '/workspace',
      '/workspace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/mcp.vue': {
      routes:
        | '/mcp'
      views:
        | never
    }
    'src/pages/meeting/index.vue': {
      routes:
        | '/meeting/'
      views:
        | never
    }
    'src/pages/meeting/[id].vue': {
      routes:
        | '/meeting/[id]'
      views:
        | never
    }
    'src/pages/plan.vue': {
      routes:
        | '/plan'
      views:
        | never
    }
    'src/pages/tasks.vue': {
      routes:
        | '/tasks'
      views:
        | never
    }
    'src/pages/test.vue': {
      routes:
        | '/test'
      views:
        | never
    }
    'src/pages/workspace.vue': {
      routes:
        | '/workspace'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
